name: eudi-verifier-integration

services:
  # === EUDI Verifier ===
  eudi-verifier-backend:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-web-verifier-endpoint-23220-4-kt:latest
#    build:
#      context: ./eudi-srv-web-verifier-endpoint-23220-4-kt
#      dockerfile: Dockerfile.custom
#      args:
#        - HTTP_PROXY=${HTTP_PROXY}
#        - HTTPS_PROXY=${HTTPS_PROXY}
#        - NO_PROXY=${NO_PROXY}
#        - NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED:-1}
#        - NEXUS_MAVEN_CENTRAL=${NEXUS_MAVEN_CENTRAL}
#        - NEXUS_MAVEN_PUBLIC=${NEXUS_MAVEN_PUBLIC}
#        - NEXUS_WALTID=${NEXUS_WALTID}
#        - NEXUS_GRADLE=${NEXUS_GRADLE}
#        - NEXUS_GRADLE_PLUGINS=${NEXUS_GRADLE_PLUGINS}
    container_name: eudi-verifier-backend
    hostname: eudi-verifier-backend
    ports:
      - "8080:8080"
    environment:
      VERIFIER_PUBLICURL: "http://verifier:8080"
      VERIFIER_RESPONSE_MODE: "DirectPostJwt"
      VERIFIER_ORIGINALCLIENTID: "verifier" # localhost
      VERIFIER_CLIENTIDPREFIX: "x509_san_dns"
      #SPRING_PROFILES_ACTIVE: "self-signed"
      VERIFIER_JAR_SIGNING_ALGORITHM: "ES512"
      VERIFIER_JAR_SIGNING_KEY: "LoadFromKeystore"
      VERIFIER_JAR_SIGNING_KEY_KEYSTORE: "classpath:keystore.jks"
      VERIFIER_JAR_SIGNING_KEY_KEYSTORE_TYPE: "jks"
      VERIFIER_JAR_SIGNING_KEY_KEYSTORE_PASSWORD: "keystore"
      VERIFIER_JAR_SIGNING_KEY_ALIAS: "verifier"
      VERIFIER_JAR_SIGNING_KEY_PASSWORD: "verifier"
      VERIFIER_VALIDATION_SDJWTVC_STATUSCHECK_ENABLED: "false"
      LOGGING_LEVEL_EU_EUROPA_EC_EUDI_VERIFIER_ENDPOINT: "DEBUG"
    restart: on-failure
    networks:
      - wallet-ecosystem_default
      - default

  #  eudi-verifier-ui:
  #    image: ghcr.io/eu-digital-identity-wallet/eudi-web-verifier:latest
  #    container_name: eudi-verifier-ui
  #    hostname: eudi-verifier-ui
  #    ports:
  #      - "4300:4300"
  #    environment:
  #      DOMAIN_NAME: ""
  #      HOST_API: "http://eudi-verifier"
  #    depends_on:
  #      - eudi-verifier-backend
  #    restart: on-failure
  #    networks:
  #      - wallet-ecosystem_default
  #      - default

  # Our custom Nuxt verifier
  custom-verifier:
    build:
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
        - NODE_OPTIONS=${NODE_OPTIONS}
        - NODE_EXTRA_CA_CERTS=${NODE_EXTRA_CA_CERTS}
      context: ../
      dockerfile: src/main/docker/Dockerfile.build
    container_name: custom-verifier
    hostname: custom-verifier
    ports:
      - "3002:3002"
    environment:
      HOST_API: "http://192.168.1.110:8080"
      PORT: "3002"
      NITRO_PORT: "3002"
      NUXT_PUBLIC_BASE_URL: "http://localhost:3002"
      PUBLIC_BASE_URL: "http://localhost:3002"
    depends_on:
      - eudi-verifier-backend
    restart: on-failure
    networks:
      - wallet-ecosystem_default
      - default

networks:
  # Connect to wallet-ecosystem network
  wallet-ecosystem_default:
    external: true
  default:
    driver: bridge
