# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: Commit Lint
on: [workflow_call] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  conform:
    name: Commit (conform) analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }} # https://github.com/actions/checkout/issues/426

      - name: Setup main branch
        run: git fetch origin main:main

      - name: Commit (conform) analysis
        uses: docker://ghcr.io/siderolabs/conform@sha256:f7e72122d4296b90285ac51964361295adf1f2018420a8547cb2b069f94a776d
        with:
          args: "enforce --base-branch=main"