# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: MegaLinter
on:
  workflow_call: # yamllint disable-line rule:truthy

permissions:
  contents: read

env:
  MEGALINTER_CONFIG: /development/megalinter.yml

jobs:
  megalinter:
    name: Megalinter analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Harden GitHub runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 10

      - name: MegaLinter lint
        id: ml
        uses: oxsecurity/megalinter@e08c2b05e3dbc40af4c23f41172ef1e068a7d651 # v8.8.0
        env:
          MEGALINTER_CONFIG: ./development/megalinter.yml
          DEFAULT_WORKSPACE: .
