# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

# Description:
# This workflow handles automated releases using the unified release system
# from diggsweden/reusable-ci for NPM packages with container images.
---
name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"              # Stable: v1.0.0
      - "v[0-9]+.[0-9]+.[0-9]+-alpha*"       # Alpha: v1.0.0-alpha.1
      - "v[0-9]+.[0-9]+.[0-9]+-beta*"        # Beta: v1.0.0-beta.1
      - "v[0-9]+.[0-9]+.[0-9]+-rc*"          # RC: v1.0.0-rc.1

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false  # Queue releases, don't cancel partial releases

permissions:
  contents: read  # Best Security practice. Jobs only get read as base, and then permissions are added as needed

jobs:
  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/v')  # Only run for version tags
    permissions:
      contents: write  # Create GitHub releases, push changelog commits
      packages: write  # Publish NPM package to GitHub registry, push to ghcr.io
      id-token: write  # Generate OIDC token for package provenance and SLSA
      actions: read    # Required for SLSA provenance generation
      security-events: write  # Upload container vulnerability scan results
      attestations: write     # Attach SBOM attestation to container images
      issues: write           # Close issues and add release comments
    uses: diggsweden/reusable-ci/.github/workflows/release-orchestrator.yml@v1
    with:
      # Project configuration
      projectType: npm  # Build system (reads version from package.json)
      branch: main      # Base branch for changelog generation
      
      # Artifact publisher configuration
      artifactPublisher: npm-app-github  # Publish to GitHub NPM registry
      # Uses default Node version (22.x)
      
      # Container builder configuration
      containerBuilder: containerimage-ghcr  # Build Docker image and push to ghcr.io
      container.platforms: "linux/amd64,linux/arm64"  # Multi-arch support for Intel and ARM
      container.containerfile: "src/main/docker/Dockerfile.build"  # Custom Dockerfile location
      # Defaults: SLSA provenance, SBOM generation enabled
      
      # NPM specific - files to commit when version changes
      file_pattern: "CHANGELOG.md package.json package-lock.json"
      
      # Changelog configuration
      changelogCreator: git-cliff  # Generate from conventional commits
      # Uses default changelog format
      
      # Release publisher configuration
      releasePublisher: github-cli         # GitHub CLI better for NPM than JReleaser
      
      # Release type auto-detected from tag (v1.0.0 = stable, v1.0.0-beta = prerelease)
    secrets: inherit  # Use org-level NPM_TOKEN and GPG keys if available
